// src/renderer.ts
import { marked } from "marked";
import * as fs from "fs";
import * as path from "path";

const PAGE_TEMPLATE = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI 日报 - {{date}}</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <nav><a href="index.html">← 返回列表</a></nav>
  <main>{{content}}</main>
  <footer>
    <p>Generated by AI Daily | <a href="https://github.com">GitHub</a></p>
  </footer>
</body>
</html>`;

const LIST_TEMPLATE = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AI 日报</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <main>
    <h1>AI 日报</h1>
    <p>每日自动生成的 AI 领域动态摘要</p>
    <hr>
    <h2>历史日报</h2>
    <ul class="digest-list">
{{items}}
    </ul>
  </main>
</body>
</html>`;

export function renderPage(markdown: string, date: string): string {
  const htmlContent = marked(markdown) as string;
  return PAGE_TEMPLATE
    .replace("{{date}}", date)
    .replace("{{content}}", htmlContent);
}

export function renderList(dates: string[]): string {
  const items = dates
    .map((date) => `      <li><a href="${date}.html">${date}</a></li>`)
    .join("\n");
  return LIST_TEMPLATE.replace("{{items}}", items);
}

export function copyStyleIfNeeded(docsDir: string): void {
  const styleSrc = path.join("templates", "style.css");
  const styleDest = path.join(docsDir, "style.css");

  if (!fs.existsSync(styleDest)) {
    fs.copyFileSync(styleSrc, styleDest);
  }
}