// src/summarizer.ts
import Anthropic from "@anthropic-ai/sdk";
import type { RssItem } from "./scrapers/rss";
import type { ArxivPaper } from "./scrapers/arxiv";
import type { GitHubRepo } from "./scrapers/github";

// 支持自定义 API base URL（兼容 GLM-5 等模型）
const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
  baseURL: process.env.ANTHROPIC_BASE_URL || undefined,
});

const SYSTEM_PROMPT = `你是 AI 领域专家，负责整理每日 AI 动态日报。

输出格式（严格遵循 Markdown）：

## 🔥 今日要闻（3-5条）
### [原标题] - 来源
> 一句话摘要（中文，100字内）
💡 点评：为什么重要（中文，50字内）

---

## 📚 论文速览（2-3篇）
### [论文标题] - arXiv
> 核心贡献一句话（中文）
📄 链接：[arXiv](url)

---

## ⭐ 值得关注的项目（1-2个）
### [仓库名] - language ⭐ stars
> 简要说明（中文）

---

## 📌 今日趋势
用 1-2 句话总结今天 AI 领域的主要动向。

---

注意：
- 标题保留原文，摘要和点评用中文
- 点评要有洞察，不要泛泛而谈
- 只保留真正重要的内容，宁缺毋滥`;

function buildRawContent(
  newsItems: RssItem[],
  papers: ArxivPaper[],
  repos: GitHubRepo[]
): string {
  const newsSection =
    newsItems.length > 0
      ? `## 今日原始资讯 (${newsItems.length} 条)\n${newsItems
          .map((i) => `- [${i.source}] ${i.title}\n  ${i.summary}`)
          .join("\n")}`
      : "## 今日原始资讯\n无";

  const papersSection =
    papers.length > 0
      ? `## 原始论文 (${papers.length} 篇)\n${papers
          .map((p) => `- ${p.title}\n  ${p.summary}`)
          .join("\n")}`
      : "## 原始论文\n无";

  const reposSection =
    repos.length > 0
      ? `## GitHub 项目 (${repos.length} 个)\n${repos
          .map((r) => `- ${r.name} ⭐${r.stars}: ${r.description}`)
          .join("\n")}`
      : "## GitHub 项目\n无";

  return `${newsSection}\n\n${papersSection}\n\n${reposSection}`;
}

export async function summarizeWithRetry(
  newsItems: RssItem[],
  papers: ArxivPaper[],
  repos: GitHubRepo[],
  retries = 3
): Promise<string> {
  const rawContent = buildRawContent(newsItems, papers, repos);
  const model = process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6";

  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      console.log(`[INFO] Claude API attempt ${attempt + 1}/${retries + 1}, model: ${model}`);
      const response = await client.messages.create({
        model,
        max_tokens: 4000,
        messages: [
          {
            role: "user",
            content: `${SYSTEM_PROMPT}\n\n---\n\n原始内容：\n\n${rawContent}`,
          },
        ],
      });

      // 查找 text 类型的内容
      for (const block of response.content) {
        if (block.type === "text") {
          return block.text;
        }
      }

      // 兼容 GLM-5 等模型的 thinking 格式
      const thinkingBlock = response.content.find((b: any) => b.type === "thinking");
      if (thinkingBlock && (thinkingBlock as any).thinking) {
        const thinkingContent = (thinkingBlock as any).thinking;
        if (thinkingContent.includes("##") || thinkingContent.length > 500) {
          return thinkingContent;
        }
      }

      // 兼容其他格式
      if (typeof response.content === "string") {
        return response.content;
      }

      throw new Error(`No text content found in response`);
    } catch (error) {
      console.warn(`[WARN] Claude API attempt ${attempt + 1} failed: ${error}`);
      if (attempt === retries) {
        throw error;
      }
      // 指数退避：5s, 15s, 45s
      const delay = 5000 * Math.pow(3, attempt);
      console.log(`[INFO] 等待 ${delay/1000}s 后重试...`);
      await new Promise((resolve) => setTimeout(resolve, delay));
    }
  }

  throw new Error("Claude API failed after retries");
}

export function generateEmptyDigest(): string {
  const today = new Date().toLocaleDateString("zh-CN");
  return `# AI 日报 - ${today}

## 📌 今日状态

今日暂无重大 AI 动态更新。

可能的原因：
- RSS 源更新延迟
- 今天是周末/假期
- API 服务波动

请明天再来查看最新动态。

---
*Generated by AI Daily*`;
}